#!/bin/sh
###############################################################################
# Copyright 2022-2025 NXP
#
# NXP Confidential and Proprietary. This software is owned or controlled by
# NXP and may only be used strictly in accordance with the applicable license
# terms.
#
# By expressly accepting such terms or by downloading, installing, activating
# and/or otherwise using the software, you are agreeing that you have read,
# and that you agree to comply with and are bound by, such license terms.
#
# If you do not agree to be bound by the applicable license terms, then you
# may not retain, install, activate or otherwise use the software.
#
###############################################################################

# set the current user as owner of installation directory
currentUser=$(echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/{print $3}')
chown -R ${currentUser}:staff "$2"

# install MCU-Link and LPCScrypt
installer -pkg "$2"/installers/LPCScrypt_2.1.4_98.pkg -target /
installer -pkg "$2"/installers/MCU-LINK_installer_3.167.pkg -target /

# create symbolic links for MCU-Link and LPCScrypt installers
# use -fn arguments to treat the link as a normal file because it is a symbolic link
# to a directory - this avoids creating a link in the layout that points to itself
ln -sfnv /Applications/lpcscrypt_2.1.4_98 "$2"/lpcscrypt
ln -sfnv /Applications/MCU-LINK_installer_3.167 "$2"/MCU-LINK_installer

# delete MCU-Link and LPCScrypt installers from layout
rm -r "$2"/installers

# Use the defaults preference system to configure installer behavior
# If the preference is not set, present the MCUXpresso IDE selection dialog; otherwise skip it 
if PREF=$(defaults read com.nxp.linkserver.installer skipIdeSelect) && [ $PREF -eq "1" ]; then
    # run the version command in the installation process 
    # to provide a faster LinkServer start-up appearance
    "$2"/LinkServer --version
else
    "$2"/LinkServer gui maint
fi
