#!/bin/bash
################################################################################
# Copyright 2018, 2023, 2025 NXP
#
# NXP Confidential and Proprietary. This software is owned or controlled by
# NXP and may only be used strictly in accordance with the applicable license
# terms.
#
# By expressly accepting such terms or by downloading, installing, activating
# and/or otherwise using the software, you are agreeing that you have read,
# and that you agree to comply with and are bound by, such license terms.
#
# If you do not agree to be bound by the applicable license terms, then you
# may not retain, install, activate or otherwise use the software.
#################################################################################

SCRIPT_HOME="$( cd "$( dirname "$0" )" && pwd )" 

name="LPC-Link"
vidpid="0x0471:0xdf55"
image="$SCRIPT_HOME/LPCXpressoWIN.enc"

$SCRIPT_HOME/dfu_boot -s $0 -n $name -v $vidpid -m R -i $image $*
